Write-Theme @("Item[0][Original Filename = US-9 13 (1)]",
" ",
"First initial contact with this 'device'.",
"Sounds like a BIRD... doesn't it?",
" ",
"I uploaded a couple of bird videos to Facebook earlier May 21st 2020.",
"(1) video of (6) Turkey Vultures flying in circles above Astoia Vucetic's land...",
"(1) video of a Peregrine Falcon that I made in Feb 2020.",
" ",
"The bird/drone showed up in response to my (audio logs/Facebook) content from that date.",
"1:00 in ****'No, no, no, no, no'**** sound as I begin walking away.")

Write-Theme @("Item[1][Original Filename = IMG_0391.MOV]",
"[Resampled] https://drive.google.com/file/d/1NAjKoFyvfcs3Ap2n-K-fmYUo6WoBNrah",
"[Original]  https://drive.google.com/file/d/1rNoF3AgiVillPHBtzH5BKcRHH47b8q0-",
" ",
"I recorded this video immediately *before* recording additional sound at 1719 US-9.",
"I have not yet recovered that recording from the device."
" ",
"The event that occurred immediately after this video, 3 Sheriff vehicles passed me while",
"I was standing near the fenced in area, followed by a blue truck.",
" ",
"I talk about this in IMG_403.")

Write-Theme @( "Item[2][Filename = New Recording 12.m4a]",
" ",
"I recorded this about an hour or two *after* first showing up at",
"Stratton Air National Guard on May 22, 2020. The date had changed to May 23, 2020.",
" ",
"I had attempted to make a recording seconds beforehand with my iPhone 8+ right before",
"I started *this* recording, using the voice memo app.",
"In the official Apple store voice memo app, the stop button pressed itself.",
"The stop button didn't press itself by the way, it was a person that was doing that",
"remotely. I've tried to tell a number of people that someone can, and has been, doing",
"this specific activity to me, but nobody bats an eye to it. They don't even ask why."
" ",
"Considering that SCSO Scott Schelling was responding to the call from Stratton",
"Air National Guard about the time I recorded this...",
"I have to assume that they are aware of the audio I recorded at College Park Hall.",
" ",
"0:00 - 'I want to record it.'",
"0:55 - (Bird/device) changes the pitch of it's 'voice', when I say 'intonation'.",
"2:24 - The high pitch of the bird was nearly unintelligible in this portion, and needed",
"( amplification + bass reduction + treble boost)",
"2:34 - The bird begins to make some type of sound which sounds like a 'handshake' for",
"modems. (15),(2),(2),(4),(16);(5);",
" ",
"3:38 - I say 'You knew I was trying to go back to UAlbany, didn't you?'",
"*Pause*",
"3:43 - 'And New Horizons...'",
"To which the (bird/device) interrupts me..."
"It sounds like the same 'No, no, no, no, no, no...' sound in the original file, US-9 13"
"Then I say 'So, New Horizons is down..?'",
"And then the (bird/device) makes the same sound, again.",
"The (bird/device) continues to make additional sounds, and I make a general assumption",
"that I'm being invited to be a teacher at this school, and that it is all because I was",
"seeking a sponsorship for my company at the time.",
"The difference in the intonation from this (bird/device) sounded like an affirmation.")

Write-Theme @("Item[3][Original Filename = IMG_0397.MOV]",
"[Resampled] https://drive.google.com/file/d/1TrmvDhzUNwOUGVI-nEwiCvz9atQ-glR2",
"[Original]  https://drive.google.com/file/d/1jJNwu1unASGinoFCl-qBVOivviSHDIBm",
" ",
"After recording the previous voice memo, I began walking along the nearby train tracks.",
"A few moments passed, and then out of sheer curiosity, I turned around and decided to",
"record this video in addition to the previous voice memo.",
" ",
"I take a moment to walk around the premises of the building.",
"My keychain is rather obvious in these resampled recordings.",
" ",
"1:00 - The bird/device begins to make a proximity sensor type sound as I approach it.",
"1:05 - 'This is exactly what I heard...' (E,E,E,E,E,E),(E,E,E,E,E)",
"1:11 - '...in Clifton Park' (F,F,F,F,F,F,F),",
"'the 1790 or whatever the' (F,F,F,F,F,F,F),",
"'building was' (F,F,F,F,F,F),",
"'the courthouse in Clifton Park' (F,F,F,F,F)",
"'across from Snyders' (G,G,G,G,G,G)",
"I'm using musical notation to describe the pattern and tone the bird is making.",
"While I am making dialogue with the (bird/device) in this recording.",
" ",
"The (bird/drone) makes a sound which sounds like an affirmation as soon as I say the",
"word 'Snyders'. The timing AND rhythm of these sounds, is what's causing me to think",
"that it's not a bird.",
" ",
"The sound that the bird is making near the end, sounds like 'DANGER', 'DANGER'...",
"It was making this sound AFTER I recorded this video of a guy walking down Route 146,",
"on May 22nd, 2020. (IMG_0391.mov)")
